apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "stage1-{{ task_instance.try_number }}-{{ macros.datetime.now().strftime('%Y-%m-%d-%H-%M') }}"
  namespace: ddt-compute
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "qxmips/spark-py:3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/from_kafka_to_minio_streaming.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 2
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.access.key": "minio"
    "fs.s3a.secret.key": "minio123"
    "fs.s3a.endpoint": "http://minio.ddt-persistence.svc.cluster.local"
    "fs.s3a.path.style.access": "true"
    "fs.s3a.connection.ssl.enabled": "false"
  # sparkConf:
  #   "spark.ui.port": "4040"
  #   "spark.eventLog.enabled": "true"
  #   "spark.eventLog.dir": "s3a://spark/eventlog"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: airflow
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
